image: mcr.microsoft.com/dotnet/sdk:6.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - publish

before_script:
  - dotnet restore

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - dotnet build

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - dotnet test

publish-Foghorn.Log-task:
  stage: publish
  script:
    - dotnet pack -c Release
    - dotnet nuget push Foghorn.Log/bin/Release/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - Foghorn.Log/*.csproj

publish-Foghorn.Logging-task:
  stage: publish
  script:
    - dotnet pack -c Release
    - dotnet nuget push Foghorn.Logging/bin/Release/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - Foghorn.Logging/*.csproj

publish-Foghorn.Logging.Slack-task:
  stage: publish
  script:
    - dotnet pack -c Release
    - dotnet nuget push Foghorn.Logging.Slack/bin/Release/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - Foghorn.Logging.Slack/*.csproj

publish-Foghorn.Logging.Gelf-task:
  stage: publish
  script:
    - dotnet pack -c Release
    - dotnet nuget push Foghorn.Logging.Gelf/bin/Release/*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - Foghorn.Logging.Gelf/*.csproj
